version: '3.8'
services:
  web:
    build: .
    ports:
      - "5002:5001"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_ENV=development
      - FLASK_APP=0.py
      - SQLALCHEMY_DATABASE_URI=sqlite:///instance/todo.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s